scopes = [
  "app",
  "args",
  "bucket",
  "config",
  "dateexp",
  "display",
  "editor",
  "entry",
  "expansion",
  "filter",
  "functions",
  "import ",
  "index",
  "input",
  "merge",
  "prelude",
  "repo",
  "sort",
  "storage",
  "sync",
  "templates",
  "templating",
  "token",
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e

echo "[Check current commit message]"
cog verify --file $1
"""

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e

echo "[Check code formatting]"
cargo fmt --check
"""

[git_hooks.pre-push]
script = """#!/bin/sh
set -e

echo "[Run clippy]"
cargo clippy -- -D warnings

echo "[Run tests]"
cargo test
"""
